### PR TITLE
Upgrade type_safe

### PR DESCRIPTION
**Pull request by saraedum**
to upgrade debug assert which fixes a `error: expected ‘{’ before ‘noexcept’` for my compiler.

### CODE REVIEW

**Comment by saraedum** [comment]
@foonathan what needs to happen to merge this?

**Comment by foonathan** [comment]
I'm trying to find time to fix the weird CI failure introduced by some environment update on the CI system.

**Comment by saraedum** [comment]
Ok. I probably don't know enough about cppast and that conan business to be of any help here.

**Comment by saraedum** [comment]
@foonathan Since this might take some more time, I think I'll use my own cppast fork then for standardese for the time being. We can't release standardese without this unfortunately. Once it's merged I'll just switch the reference in standardese back.

**Comment by foonathan** [comment]
I have updated it myself now.

**Pull request closed without merging**
