### PR TITLE
Add forward declarations

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@foonathan would you mind adding forward declarations for all the non-detail types?

This would make my life at standardese slightly easier as I could just include this in a few places without worrying about compile times.

**Comment by foonathan** [comment]
Works for me, thank you for the PR. I have two minor issues:

* I don't really like the name: when I hear `forward.hpp` I think `std::forward`. But I don't really have a good alternative.
* What types are forward declared here? Is it everything in all headers or just a selected subset? I have a slight preference to a header that forward declares only the AST classes, not the parsing and formatting stuff. Would that work for you as well?

**Comment by saraedum** [comment]
> I like the idea in principle, thank you for the PR. I have two minor issues:
> 
>     * I don't really like the name: when I hear `forward.hpp` I think `std::forward`. But I don't really have a good alternative.

I agree that `forward` can be misleading. The standard library has `iosfwd` but I am not sure whether `cppastfwd` would make things any easier to understand.

>     * What types are forward declared here? Is it everything in all headers or just a selected subset? I have a slight preference to a header that forward declares only the AST classes, not the parsing and formatting stuff. Would that work for you as well?

If I did not nothing wrong, these are all the types not in any `details` namespace. I only need the AST classes so I am fine with removing everything else.

**Comment by foonathan** [comment]
Then I suggest you add a new header `cpp_entity_fwd.hpp` and forward declare the AST classes only there.

**Comment by foonathan** [comment]
Any update on this?

**Comment by saraedum** [comment]
I was planning to fix this up when I am mostly done with my changes for standardese 0.6.0. So, it's certainly not forgotten since I use this header extensively in 0.6.0.

**Comment by saraedum** [comment]
Looking at this again, I am not sure it's so easy to draw a line what to include and what not to include here.

This forward header should certainly include all the AST classes. But I guess it should also include all the related enums? Then maybe, it's easier to just include everything that's not `detail`. It does not really matter in terms of parsing time how much we include and I feel it's more practical to just include all the types in the API.

So, maybe we just rename this to `cppast_fwd.hpp`?

**Comment by saraedum** [comment]
Does the macOS error have anything to with what I did here or is that expected?

**Comment by foonathan** [comment]
No, those are a separate issue. I'll fix that this week and then I can merge the PR.

**Pull request merged**
