### PR TITLE
Support for parsing entities ignored by the libclang AST (And more :P)

### PR DESCRIPTION
**Pull request by Manu343726**
This PR implements a parser API with its own AST to parse interesting entities that are ignored by the current cppast backends (i.e. our beloved libclang). The API, defined as part of the `detail` module, works as follows:

 - **A live (scanning) lexer API** with features to easily implement LL(k) parsers. An implementation using `std::istream` as input is given. Also a fake lexer to feed a parser with libclang tokens is implemented.
 - **A simple LL(1) parser**: The parser implements a language of simple invoke expressions (See the parser docs for the grammar), which each grammar production implemented as an overridable method. This way the parser can be extended and customized to implement other grammars.
 - **An isolated AST hierarchy**: The result of parsing is an AST defined as part of the API, supporting the grammar mentioned above. The AST **does not include semantic analysis** (That will come later, since matchers would help a lot on that matter).
 - **Extraction of the AST of a "C++" attribute**: The parser implements parsing of a C++ attribute. As the docs state, the parser of attributes is not 100% compliant, but works for the majority of the potential use cases (`[[foo]]`, `[[deprecated("foo")]]`, `[[gnu::foobar]]`, etc).  
**EDIT:** I will put the C++ BNF grammar here as reference, it should be really easy to follow that grammar to be 100% compliant (Actually, that grammar seems simple than my `CppAttrExpr := [[InvokeExpr]]`) http://www.nongnu.org/hcb/#attribute-specifier 

Some notes:

 - Looking at the work now, the first four commits could be squashed to ease with the review.
 - While the API uses [fmt](https://github.com/fmtlib/fmt), the dependency is optional and disabled by default, switching to a custom (And horribly slow...) alternative I wrote as fallback. The fmt dep can be enabled with `CPPAST_USE_FMT` cmake var.
 - The implementation includes two example files to show the usage of the API, but since cppast does not currently include an `examples/` directory, I've placed these in `src/detail/parser/`, the directory of the API.
 - The PR also implements a code coverage target using lcov, and submission of coverage data to coveralls.io. (Great news: You do not need to change anything from the CI script, auth and submission is already handled by the coveralls client which detects its running from a Travis CI build, you only have to enable `foonathan/cppast` on coveralls.io to make it work). Code coverage is enabled with `CPPAST_TEST_GCOV` cmake var.
 - I've added badges to the readme. Badges are cool :)
 - The PR still lacks your requests about `ts::object_ref` etc, since I was sure a lot of more requests like that will come from the review.
 - Maybe Boost.Spirit was an option after all....
 - I'm happy to hear about squashes. These are 32 commits.

### CODE REVIEW

**Comment by Manu343726** [comment]
Ok, the GCC 7 job is failing. What's the diff between your environment and this https://travis-ci.org/Manu343726/cppast?

**Comment by foonathan** [comment]
Its on a different Ubuntu version because it is newer I guess: https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default

**Comment by Manu343726** [comment]
I see. I added a GCC 7 job bc it is the gcc I have on my laptop and I had been having problems with fmt (See https://github.com/fmtlib/fmt/issues/552), the job was a way to try to show my exact use case. We could update your CI environment to trusty (how?) or remove it if you prefer. Or downgrade it to gcc 5 since it is the only job running with fmt enabled.

**Comment by Manu343726** [comment]
btw are appveyor builds up to date?

**Comment by foonathan** [comment]
FYI, I've started to cherry pick individual smaller changes and merge them like code coverage.

**Comment by foonathan** [comment]
FYI, I've started to cherry pick individual smaller changes and merge them, like code coverage.

I've also copied the diagnostic improvements but instead of adding the whole format dependency, I've just used my ghetto format that simply streams each argument in turn.

**Comment by foonathan** [comment]
I'm currently working on integrating your lexers. I'm going to change them a bit to use my new cpp_token facility and probably rename them to tokenizer for consistency etc.

**Comment by Manu343726** [comment]
@foonathan I'm glad you cherry-pick what you're currently interested first. Feel free to ping me for questions/feedback :)

**Comment by foonathan** [comment]
Okay, I think your parsing stuff is overkill for my situation.

I have just written a simple tokenizer (which assumes valid tokens but this is fine for this use case) in order to convert a string into my `cpp_token_string`. Your lexers are great but I think just too much.

And the grammar for attributes is actually much more free form than you've implemented (as I can tell). It is literally just any namespace + identifier + arguments where the arguments are *any* sequence of tokens, so I don't need anything fancy for that either.

Anyways, thanks a lot for your pull request.

**Comment by Manu343726** [comment]
Iirc we already talked about this, this PR was my approach to the first
step for a much wider feature I'm working on, so it's completely reasonable
(at least for me) that if this specific features don't suit your needs (or
even become an overkill for your current use case) you reject this PR in
its current form.

 I will be continue working (you know my roadmap) and will ping you from
time to time to try to integrate the results of my work into your lib, in
case that makes sense of course ;)

BTW, about the attributes grammar, you're right, that parser was like "oh,
matchers surrounded by brackets are valid attributes, let's play with this!"
...

As usual, I'm glad to help in any way (Q/A, chat, brainstorming, etc).

On Oct 19, 2017 18:16, "Jonathan Müller" <notifications@github.com> wrote:

Closed #23 <https://github.com/foonathan/cppast/pull/23>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/foonathan/cppast/pull/23#event-1301540016>, or mute the
thread

**Pull request closed without merging**
