### PR TITLE
Remove llvm-config requirement

### PR DESCRIPTION
**Pull request by ReDucTor**

### CODE REVIEW

**Comment by ReDucTor** [comment]
Will look to resolve build failures, then get this ready to merge. However probably won't be for another couple of days, good to get any feedback in the mean time

**Comment by foonathan** [comment]
What are you trying to do exactly?

**Comment by ReDucTor** [comment]
The goal is to aid the detection of clang on windows when installed from the downloaded binary package, instead of the instructions for windows still saying to build llvm/clang

**Comment by foonathan** [comment]
Are you still trying to fix this?

**Comment by ReDucTor** [comment]
Moved onto other things, will close it for now and resurrect if I start looking at it again.

**Pull request closed without merging**
