### PR TITLE
Parse C++17 nested namespace declarations

### PR DESCRIPTION
**Pull request by topisani**
This is maybe not the most correct way to do it, but i dont think it misparses
any valid code. Tested on [topisani/OTTO](https://github.com/topisani/OTTO), and seems to work.

### CODE REVIEW

**Comment by foonathan** [comment]
I'm going to implement them properly - parsing the entire name, so closing this one.

**Comment by foonathan** [comment]
I don't get your parsing code, if skipping `namespace` fails, why does `::` work?

Is it because you'll only get the nested part of the name?

**Comment by topisani** [comment]
```cpp
namespace an::example {
```
This gives you this AST structure:
```
NamespaceCursor: "namespace an"
  +- NamespaceCursor "::example"
```
therefore when parsing, we first have to skip either `namespace` or `::`

**Comment by foonathan** [comment]
Okay, I get it.

Could you add a comment explaining exactly that?
And also a simple test case so the coveralls bot is happy?

**Comment by topisani** [comment]
on it!

**Comment by topisani** [comment]
Is there actually any reason to skip the last `{`? the stream is destroyed anyway

**Comment by foonathan** [comment]
This is just to catch potential errors.

**Comment by foonathan** [comment]
Yes, `\entity` doesn't work (it is done at the level of standardese).

I've fixed it by letting the nested namespace steal the comment from the parent.
Thank you, I'm closing this as I've merged it maually into my branch.

**Comment by topisani** [comment]
Optimally, i think only the most nested namespace should get the comment. At least that makes most sense in the case of standardese, but this might be an issue there

**Pull request closed without merging**
